# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face_recognition.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'face_recognition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66\x61\x63\x65_recognition.proto\x12\x10\x66\x61\x63\x65_recognition\".\n\x0cImageRequest\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12\x0e\n\x06labels\x18\x02 \x03(\t\"1\n\rImageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rResultRequest\"E\n\x0eResultResponse\x12\x18\n\x10processed_images\x18\x01 \x03(\x0c\x12\x19\n\x11recognized_labels\x18\x02 \x03(\t2\xb1\x01\n\x0f\x46\x61\x63\x65Recognition\x12M\n\nSendImages\x12\x1e.face_recognition.ImageRequest\x1a\x1f.face_recognition.ImageResponse\x12O\n\nGetResults\x12\x1f.face_recognition.ResultRequest\x1a .face_recognition.ResultResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_recognition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=44
  _globals['_IMAGEREQUEST']._serialized_end=90
  _globals['_IMAGERESPONSE']._serialized_start=92
  _globals['_IMAGERESPONSE']._serialized_end=141
  _globals['_RESULTREQUEST']._serialized_start=143
  _globals['_RESULTREQUEST']._serialized_end=158
  _globals['_RESULTRESPONSE']._serialized_start=160
  _globals['_RESULTRESPONSE']._serialized_end=229
  _globals['_FACERECOGNITION']._serialized_start=232
  _globals['_FACERECOGNITION']._serialized_end=409
# @@protoc_insertion_point(module_scope)
