syntax = "proto3";

package face_recognition;

service FaceRecognition {
  rpc SendImages (ImageRequest) returns (ImageResponse);
  rpc GetResults (ResultRequest) returns (ResultResponse);
}

message ImageRequest {
  repeated bytes images = 1;
  repeated string labels = 2;
}

message ImageResponse {
  bool success = 1;
  string message = 2;
}

message ResultRequest {
}

message ProcessedFrame {
  bytes frame = 1;
  repeated bytes cropped_faces = 2;
  repeated string recognized_labels = 3;
}

message CamerasObject {
  int32 camera_index = 1;
  repeated ProcessedFrame frames = 2;
}

message ResultResponse {
  repeated CamerasObject response = 1;
}